export const authTypes = {
  LOGIN_REQUEST: "LOGIN_REQUEST",
  LOGIN_FAILURE: "LOGIN_FAILURE",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGOUT_REQUEST: "LOGOUT_REQUEST",
  LOGOUT_SUCCESS: "LOGOUT_SUCCESS",
  LOGOUT_FAILURE: "LOGOUT_FAILURE",
};

export const categoryTypes = {
  GET_ALL_CATEGORY_REQUEST: "GET_ALL_CATEGORY_REQUEST",
  GET_ALL_CATEGORY_SUCCESS: "GET_ALL_CATEGORY_SUCCESS",
  GET_ALL_CATEGORY_FAILURE: "GET_ALL_CATEGORY_FAILURE",
  ADD_CATEGORY_REQUEST: "ADD_CATEGORY_REQUEST",
  ADD_CATEGORY_SUCCESS: "ADD_CATEGORY_SUCCESS",
  ADD_CATEGORY_FAILURE: "ADD_CATEGORY_FAILURE",
};

export const productTypes = {
  GET_PRODUCTS_BY_CATEGORY_SLUG_REQUEST:
    "GET_PRODUCTS_BY_CATEGORY_SLUG_REQUEST",
  GET_PRODUCTS_BY_CATEGORY_SLUG_SUCCESS:
    "GET_PRODUCTS_BY_CATEGORY_SLUG_SUCCESS",
  GET_PRODUCTS_BY_CATEGORY_SLUG_FAILURE:
    "GET_PRODUCTS_BY_CATEGORY_SLUG_FAILURE",
  GET_PRODUCT_PAGE_REQUEST: " GET_PRODUCT_PAGE_REQUEST",
  GET_PRODUCT_PAGE_SUCCESS: " GET_PRODUCT_PAGE_SUCCESS",
  GET_PRODUCT_PAGE_FAILURE: " GET_PRODUCT_PAGE_FAILURE",
};
